# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='schemainspect',
    version='0.2',
    description='Schema inspection for PostgreSQL (and possibly others)',
    project_urls={
        "homepage": "https://github.com/djrobstep/schemainspect",
        "repository": "https://github.com/djrobstep/schemainspect"
    },
    author='Robert Lechte',
    author_email='robertlechte@gmail.com',
    license='Unlicense',
    packages=['schemainspect', 'schemainspect.pg'],
    package_dir={"": "."},
    package_data={"schemainspect.pg": ["sql/*.sql"]},
    install_requires=['six', 'sqlalchemy'],
    extras_require={
        "dev": [
            "black>=19.10b0; python_version >= \"3.6\"", "flake8", "isort",
            "migra", "psycopg2-binary", "pytest", "pytest-cov", "pytest-sugar",
            "sqlbag"
        ]
    },
)
